componentName: user
appPort: 8080
appVersion: 3.0.1
externalSecret:
  enabled: true
resources:
   limits:
     cpu: 250m
     memory: 350Mi
   requests:
     cpu: 200m
     memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
healthEndpoint: /health
